---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "Hogfish"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_groups/biomass/hogfish_fk_bio.csv",
title   = "Hogfish biomass",
y_label = "biomass",
skip    = 0,
filter  = NULL,
col_t   = "year",
col_y   = "biomass"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/exploited_species/exploited_fk_bio.csv",
title   = "Hogfish biomass",
y_label = "biomass",
skip    = 0,
filter  = "SPECIES_CD == \"LAC MAXI\"",
col_t   = "year",
col_y   = "biomass"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_groups/density/hogfish_fk_den.csv",
title   = "Hogfish Density",
y_label = "Density",
skip    = 0,
filter  = NULL,
col_t   = "year",
col_y   = "density"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/exploited_species/exploited_fk_den.csv",
title   = "Hogfish Density",
y_label = "Density",
skip    = 0,
filter  = "SPECIES_CD == \"LAC MAXI\"",
col_t   = "year",
col_y   = "density"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_groups/diversity/hogfish_fk_diversity.csv",
title   = "Hogfish Richness",
y_label = "Species Richness",
skip    = 0,
filter  = NULL,
col_t   = "year",
col_y   = "richness"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_groups/diversity/hogfish_fk_diversity.csv",
title   = "Hogfish Shannon Diversity",
y_label = "Effective number of species",
skip    = 0,
filter  = NULL,
col_t   = "year",
col_y   = "shannon"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_groups/diversity/hogfish_fk_diversity.csv",
title   = "Hogfish Simpson Diversity",
y_label = "Effective number of species",
skip    = 0,
filter  = NULL,
col_t   = "year",
col_y   = "simpson"),
error = function(e) e)
```
