---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "trophhic level pyramid"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_level/tlbio.csv",
title   = "Trophic Level",
y_label = "Biomass",
skip    = 0,
filter  = "TL == 1",
col_t   = "year",
col_y   = "biomass"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_level/tlbio.csv",
title   = "Trophic Level",
y_label = "Biomass",
skip    = 0,
filter  = "TL == 1",
col_t   = "year",
col_y   = "biomass"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_level/tlbio.csv",
title   = "Trophic Level",
y_label = "Biomass",
skip    = 0,
filter  = "TL == 1",
col_t   = "year",
col_y   = "biomass"),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "https://github.com/mhepner90/RVC/blob/master/trophic_level/tlbio.csv",
title   = "Trophic Level",
y_label = "Biomass",
skip    = 0,
filter  = "TL == 1",
col_t   = "year",
col_y   = "biomass"),
error = function(e) e)
```
